version: '2'

services:
    buildandroidndk:
        image: ubuntu-build-android:latest
        volumes:
            - ".:/source"
        entrypoint: /src/bin-build/android-arm64.sh
        environment:
            MYSQL_HOST: "mysqldb"
            POSTGRESQL_HOST: "postgresdb"
            REDIS_HOST: "redisdb"
            MONGODB_HOST: "mongodb"
            POCO_TEST_POSTGRES_CONN: "DATABASE=postgres;SERVER=postgres;PORT=5432;"
        depends_on:
            - mysqldb
            - redisdb
            - postgresdb
            - mongodb
        networks:
            - mynet
