version: '2'

services:
    buildmingw:
        image: ubuntu-build-mingw:latest
        volumes:
            - ".:/src"
            - "/home/joerg/Development/cmake-tools:/cmake-tools"
        entrypoint: /src/bin-build/cmake-mingw.sh
        environment:
            MYSQL_HOST: "mysqldb"
            POSTGRESQL_HOST: "postgresdb"
            REDIS_HOST: "redisdb"
            MONGODB_HOST: "mongodb"
            POCO_TEST_POSTGRES_CONN: "DATABASE=postgres;SERVER=postgres;PORT=5432;"
        depends_on:
            - mysqldb
            - redisdb
            - postgresdb
            - mongodb
        networks:
            - mynet
