#!/bin/sh

SRC_DIR=/src/poco
BUILD_DIR=~/poco-docker
CMAKE_EXECUTE="cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 "
CUR_DIR=`pwd`
BUILD_TYPES="Debug Release NONE"
WITH_FEATURES="ENABLE_WSTRING ENABLE_FPENVIRONMENT ENABLE_POCODOC"
WITH_TYPES="ENABLE_TESTS NONE"
COMPONENTS_ON="ENABLE_ENCODINGS ENABLE_ENCODINGS_COMPILER ENABLE_XML ENABLE_JSON ENABLE_MONGODB ENABLE_PDF ENABLE_UTIL ENABLE_NET ENABLE_NETSSL ENABLE_CRYPTO ENABLE_DATA ENABLE_DATA_SQLITE ENABLE_DATA_MYSQL ENABLE_DATA_ODBC ENABLE_SEVENZIP ENABLE_ZIP ENABLE_APACHECONNECTOR ENABLE_CPPPARSER ENABLE_PAGECOMPILER ENABLE_PAGECOMPILER_FILE2PAGE ENABLE_REDIS"
COMPONENTS_OFF="ENABLE_ENCODINGS ENABLE_ENCODINGS_COMPILER ENABLE_XML ENABLE_JSON ENABLE_MONGODB ENABLE_PDF ENABLE_UTIL ENABLE_NET ENABLE_NETSSL ENABLE_CRYPTO ENABLE_DATA ENABLE_DATA_SQLITE ENABLE_DATA_MYSQL ENABLE_DATA_ODBC ENABLE_SEVENZIP ENABLE_ZIP ENABLE_APACHECONNECTOR ENABLE_CPPPARSER ENABLE_PAGECOMPILER ENABLE_PAGECOMPILER_FILE2PAGE ENABLE_REDIS"

rm -fr $BUILD_DIR

for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPON in $COMPONENTS_ON; do
	    for COPOFF in $COMPONENTS_OFF; do
		if [ "$COPON" = "$COPOFF" ]; then
		    COMPONENT="$COMPONENT -D$COPON=ON"
		    COPON="-"
		else
		    COMPONENT="$COMPONENT -D$COPOFF=OFF"
		fi
	    done
	    if [ "$BUILD_TYPE" != "NONE" ]; then
		CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	    fi
	    if [ "$WITH_TYPE" != "NONE" ]; then
		CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	    fi
	    CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	    echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure"
	    $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all #&& cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure
	    cd $CUR_DIR
	    rm -fr $BUILD_DIR
	    COMPONENT=""
	    CMAKE_PARAMETER=""
	done    
    done
done

for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPOFF in $COMPONENTS_OFF; do
	    COMPONENT="$COMPONENT -D$COPOFF=OFF"
	done
	if [ "$BUILD_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	fi
	if [ "$WITH_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	fi
	CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure"
	$CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all #&& cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure
	cd $CUR_DIR
	rm -fr $BUILD_DIR
	COMPONENT=""
	CMAKE_PARAMETER=""
    done
done

for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPON in $COMPONENTS_ON; do
	    COMPONENT="$COMPONENT -D$COPON=ON"
	done
	if [ "$BUILD_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	fi
	if [ "$WITH_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	fi
	CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure"
	$CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && BASE=$SRC_DIR ctest --output-on-failure
	cd $CUR_DIR
	rm -fr $BUILD_DIR
	COMPONENT=""
	CMAKE_PARAMETER=""
    done
done

# -DCMAKE_BUILD_TYPE=Debug 
# cmake -H$SRC_DIR -B$BUILD_DIR -GNinja \
# -DCMAKE_VERBOSE_MAKEFILE=true \
# -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 \
# -DENABLE_PDF=OFF \
# -DENABLE_ENCODINGS=OFF \
# -DENABLE_TESTS=ON \
# -DENABLE_XML=OFF \
# -DENABLE_JSON=OFF \
# -DENABLE_MONGODB=OFF \
# -DENABLE_UTIL=OFF \
# -DENABLE_NET=OFF \
# -DENABLE_CRYPTO=OFF \
# -DENABLE_NETSSL=OFF \
# -DENABLE_SQL=OFF \
# -DENABLE_SQL_SQLITE=OFF \
# -DENABLE_SQL_MYSQL=OFF \
# -DENABLE_SQL_POSTGRESQL=OFF \
# -DENABLE_SQL_ODBC=OFF \
# -DENABLE_SEVENZIP=OFF \
# -DENABLE_ZIP=OFF \
# -DENABLE_APACHECONNECTOR=OFF \
# -DENABLE_CPPPARSER=OFF \
# -DENABLE_POCODOC=OFF \
# -DENABLE_PAGECOMPILER=OFF \
# -DENABLE_PAGECOMPILER_FILE2PAGE=OFF \
# -DENABLE_REDIS=OFF \
# -DENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=OFF -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_VERBOSE_MAKEFILE=true -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_BUILD_TYPE=Debug -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON && \
# cmake --build $BUILD_DIR --target all && \
#cd $BUILD_DIR && BASE=$SRC_DIR ctest -VV --output-on-failure
#cd $BUILD_DIR && BASE=$SRC_DIR ctest -VV || \
#cd $BUILD_DIR/bin && BASE=$SRC_DIR ./Foundation-testrunner SharedLibraryTestSuite
#/bin/bash
