#!/bin/sh -x

SRC_DIR=/src
BUILD_DIR=/build/poco-docker

#-DCMAKE_BUILD_TYPE=Debug 
# cmake -H$SRC_DIR -B$BUILD_DIR -GNinja \
# -DCMAKE_VERBOSE_MAKEFILE=true \
# -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 \
# -DPOCO_ENABLE_PDF=OFF \
# -DPOCO_ENABLE_ENCODINGS=OFF \
# -DPOCO_ENABLE_TESTS=ON \
# -DPOCO_ENABLE_XML=OFF \
# -DPOCO_ENABLE_JSON=OFF \
# -DPOCO_ENABLE_MONGODB=OFF \
# -DPOCO_ENABLE_UTIL=OFF \
# -DPOCO_ENABLE_NET=OFF \
# -DPOCO_ENABLE_CRYPTO=OFF \
# -DPOCO_ENABLE_NETSSL=OFF \
# -DPOCO_ENABLE_SQL=OFF \
# -DPOCO_ENABLE_SQL_SQLITE=OFF \
# -DPOCO_ENABLE_SQL_MYSQL=OFF \
# -DPOCO_ENABLE_SQL_POSTGRESQL=OFF \
# -DPOCO_ENABLE_SQL_ODBC=OFF \
# -DPOCO_ENABLE_SEVENZIP=OFF \
# -DPOCO_ENABLE_ZIP=OFF \
# -DPOCO_ENABLE_APACHECONNECTOR=OFF \
# -DPOCO_ENABLE_CPPPARSER=OFF \
# -DPOCO_ENABLE_POCODOC=OFF \
# -DPOCO_ENABLE_PAGECOMPILER=OFF \
# -DPOCO_ENABLE_PAGECOMPILER_FILE2PAGE=OFF \
# -DPOCO_ENABLE_REDIS=OFF \
# -DPOCO_ENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=OFF -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_VERBOSE_MAKEFILE=true -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=ON && \
cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_BUILD_TYPE=Debug -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=ON && \
cmake --build $BUILD_DIR --target all && \
#cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest -VV --output-on-failure
cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest -VV || \
#cd $BUILD_DIR/bin && POCO_BASE=$SRC_DIR ./Foundation-testrunner SharedLibraryTestSuite
/bin/bash
