#!/bin/sh

SRC_DIR=/src/poco
BUILD_DIR=/build/poco-docker
CMAKE_EXECUTE="cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0" # -DCMAKE_VERBOSE_MAKEFILE=true"
CUR_DIR=`pwd`
BUILD_TYPES="Debug Release NONE"
WITH_FEATURES="POCO_ENABLE_WSTRING POCO_ENABLE_FPENVIRONMENT POCO_ENABLE_POCODOC"
WITH_TYPES="POCO_ENABLE_TESTS POCO_ENABLE_SAMPLES NONE"
COMPONENTS_ON="POCO_ENABLE_CPPUNIT POCO_ENABLE_ENCODINGS POCO_ENABLE_ENCODINGS_COMPILER POCO_ENABLE_XML POCO_ENABLE_JSON POCO_ENABLE_MONGODB POCO_ENABLE_PDF POCO_ENABLE_UTIL POCO_ENABLE_NET POCO_ENABLE_NETSSL POCO_ENABLE_CRYPTO POCO_ENABLE_SQL POCO_ENABLE_SQL_SQLITE POCO_ENABLE_SQL_MYSQL POCO_ENABLE_SQL_POSTGRESQL POCO_ENABLE_SQL_ODBC POCO_ENABLE_SEVENZIP POCO_ENABLE_ZIP POCO_ENABLE_APACHECONNECTOR POCO_ENABLE_CPPPARSER POCO_ENABLE_PAGECOMPILER POCO_ENABLE_PAGECOMPILER_FILE2PAGE POCO_ENABLE_REDIS"
COMPONENTS_OFF="POCO_ENABLE_CPPUNIT POCO_ENABLE_ENCODINGS POCO_ENABLE_ENCODINGS_COMPILER POCO_ENABLE_XML POCO_ENABLE_JSON POCO_ENABLE_MONGODB POCO_ENABLE_PDF POCO_ENABLE_UTIL POCO_ENABLE_NET POCO_ENABLE_NETSSL POCO_ENABLE_CRYPTO POCO_ENABLE_SQL POCO_ENABLE_SQL_SQLITE POCO_ENABLE_SQL_MYSQL POCO_ENABLE_SQL_POSTGRESQL POCO_ENABLE_SQL_ODBC POCO_ENABLE_SEVENZIP POCO_ENABLE_ZIP POCO_ENABLE_APACHECONNECTOR POCO_ENABLE_CPPPARSER POCO_ENABLE_PAGECOMPILER POCO_ENABLE_PAGECOMPILER_FILE2PAGE POCO_ENABLE_REDIS"

rm -fr $BUILD_DIR

for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPON in $COMPONENTS_ON; do
	    for COPOFF in $COMPONENTS_OFF; do
		if [ "$COPON" = "$COPOFF" ]; then
		    COMPONENT="$COMPONENT -D$COPON=ON"
		    COPON="-"
		else
		    COMPONENT="$COMPONENT -D$COPOFF=OFF"
		fi
	    done
	    if [ "$BUILD_TYPE" != "NONE" ]; then
		CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	    fi
	    if [ "$WITH_TYPE" != "NONE" ]; then
		CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	    fi
	    CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	    echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure"
	    $CMAKE_EXECUTE $CMAKE_PARAMETER #&& cmake --build $BUILD_DIR --target all #&& cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure
	    cd $CUR_DIR
	    rm -fr $BUILD_DIR
	    COMPONENT=""
	    CMAKE_PARAMETER=""
	done    
    done
done
 
for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPOFF in $COMPONENTS_OFF; do
	    COMPONENT="$COMPONENT -D$COPOFF=OFF"
	done
	if [ "$BUILD_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	fi
	if [ "$WITH_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	fi
	CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure"
	$CMAKE_EXECUTE $CMAKE_PARAMETER #&& cmake --build $BUILD_DIR --target all #&& cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure
	cd $CUR_DIR
	rm -fr $BUILD_DIR
	COMPONENT=""
	CMAKE_PARAMETER=""
    done
done

for BUILD_TYPE in $BUILD_TYPES; do
    for WITH_TYPE in $WITH_TYPES; do
	for COPON in $COMPONENTS_ON; do
	    COMPONENT="$COMPONENT -D$COPON=ON"
	done
	if [ "$BUILD_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="-DCMAKE_BUILD_TYPE=$BUILD_TYPE"
	fi
	if [ "$WITH_TYPE" != "NONE" ]; then
	    CMAKE_PARAMETER="$CMAKE_PARAMETER -D$WITH_TYPE=ON"
	fi
	CMAKE_PARAMETER="$CMAKE_PARAMETER $COMPONENT"
	echo "cmake execution: $CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure"
	$CMAKE_EXECUTE $CMAKE_PARAMETER && cmake --build $BUILD_DIR --target all && cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest --output-on-failure
	cd $CUR_DIR
	rm -fr $BUILD_DIR
	COMPONENT=""
	CMAKE_PARAMETER=""
    done
done

# -DCMAKE_BUILD_TYPE=Debug 
# cmake -H$SRC_DIR -B$BUILD_DIR -GNinja \
# -DCMAKE_VERBOSE_MAKEFILE=true \
# -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 \
# -DPOCO_ENABLE_PDF=OFF \
# -DPOCO_ENABLE_ENCODINGS=OFF \
# -DPOCO_ENABLE_TESTS=ON \
# -DPOCO_ENABLE_XML=OFF \
# -DPOCO_ENABLE_JSON=OFF \
# -DPOCO_ENABLE_MONGODB=OFF \
# -DPOCO_ENABLE_UTIL=OFF \
# -DPOCO_ENABLE_NET=OFF \
# -DPOCO_ENABLE_CRYPTO=OFF \
# -DPOCO_ENABLE_NETSSL=OFF \
# -DPOCO_ENABLE_SQL=OFF \
# -DPOCO_ENABLE_SQL_SQLITE=OFF \
# -DPOCO_ENABLE_SQL_MYSQL=OFF \
# -DPOCO_ENABLE_SQL_POSTGRESQL=OFF \
# -DPOCO_ENABLE_SQL_ODBC=OFF \
# -DPOCO_ENABLE_SEVENZIP=OFF \
# -DPOCO_ENABLE_ZIP=OFF \
# -DPOCO_ENABLE_APACHECONNECTOR=OFF \
# -DPOCO_ENABLE_CPPPARSER=OFF \
# -DPOCO_ENABLE_POCODOC=OFF \
# -DPOCO_ENABLE_PAGECOMPILER=OFF \
# -DPOCO_ENABLE_PAGECOMPILER_FILE2PAGE=OFF \
# -DPOCO_ENABLE_REDIS=OFF \
# -DPOCO_ENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=OFF -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=OFF && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_VERBOSE_MAKEFILE=true -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=ON && \
#cmake -H$SRC_DIR -B$BUILD_DIR -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DCMAKE_VERBOSE_MAKEFILE=true -DCMAKE_BUILD_TYPE=Debug -DENABLE_PDF=OFF -DENABLE_TESTS=ON -DENABLE_SAMPLES=ON -DPOCO_ENABLE_PDF=OFF -DPOCO_ENABLE_TESTS=ON -DPOCO_ENABLE_SAMPLES=ON && \
# cmake --build $BUILD_DIR --target all && \
#cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest -VV --output-on-failure
#cd $BUILD_DIR && POCO_BASE=$SRC_DIR ctest -VV || \
#cd $BUILD_DIR/bin && POCO_BASE=$SRC_DIR ./Foundation-testrunner SharedLibraryTestSuite
#/bin/bash
